import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

import Convex_Client_Provider from "@/providers/convex.client.provider";
import { Model_Provider } from "@/providers/model-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Convex_Client_Provider>
          <Toaster />

          <Model_Provider />
          {children}
        </Convex_Client_Provider>
      </body>
    </html>
  );
}
